substitutions:
  devicename: hp-psu-example
  upper_devicename: hp-psu-example
  api_encryption_key: < REPLACE - USE GENERATED >
  ota_password: < REPLACE - USE GENERATED >
  ap_password: < REPLACE - USE GENERATED >
  ip: 10.0.0.109
  subnet: 255.255.255.0
  gateway: 10.0.0.1

  enable_psu1: "true"   # set to true to enable, false to disable
  enable_psu2: "true"   # set to true to enable, false to disable
  enable_psu3: "false"  # set to true to enable, false to disable
  enable_psu4: "false"  # set to true to enable, false to disable

<<: !include ./common/HPPSU_CTRL_r2.0.yaml
